package Draw;

/**
 * Enum of all waytypes
 */
public enum WayType {
	UNKNOWN, BUILDING, WATER, COASTLINE, LANDUSE_RESIDENTIAL, AMENITY_SCHOOL, LANDUSE_ALLOTMENTS, LANDUSE_GRASS, LANDUSE_SPORTS_CENTRE, LANDUSE_TRACK, LANDUSE_PARK, LANDUSE_PLAYGROUND, AMENITY_MARKETPLACE, LANDUSE_INDUSTRIAL, LANDUSE_HOSPITAL, LEISURE_PITCH, LANDUSE_RESERVOIR, MAN_MADE_PITCH, NATURAL_BEACH, MAN_MADE_BREAKWATER, HIGHWAY_SECONDARY, HIGHWAY_RESIDENTIAL, HIGHWAY_TERTIARY, LANDUSE_FOREST, LANDUSE_FARMLAND, LANDUSE_FARMYARD, HIGHWAY_SERVICE, AMENITY_PARKING, AEROWAY_AERODROME, AEROWAY_HELIPAD, AEROWAY_RUNWAY, AEROWAY_TAXIWAY, AEROWAY_APRON, HIGHWAY_CYCLEWAY, HIGHWAY_TRACK, POWER_GENERATOR, HIGHWAY_FOOTWAY, AMENITY_BUS_STATION, HIGHWAY_STEPS, HIGHWAY_UNCLASSIFIED, TOURISM_CAMP_SITE, NATURAL_SCRUB, TOURISM_THEME_PARK, WATERWAY_DITCH, NATURAL_HEATH, AMENITY_TAXI, LANDUSE_BASIN, HIGHWAY_PATH, HIGHWAY_BARE_ROCK, HIGHWAY_PRIMARY, WATERWAY_STREAM, LANDUSE_MEADOW, MAN_MADE_PIER, Natural_BARE_ROCK, NATURAL_SAND, POI_MARKER, POI_VISIT, CARTOGRAPHIC_BUS_STOP, CARTOGRAPHIC_SHOP, AMENITY_HOSPITAL, CARTOGRAPHIC_HOSPITAL, HIGHWAY_MOTORWAY, HIGHWAY_MOTORWAY_LINK, POI_PIN,CARTOGRAPHIC_TAXI,CARTOGRAPHIC_PARKING,CARTOGRAPHIC_CAFE;
}
